### ISSUE TITLE
Missing / in CDN URL

### ISSUE THREAD

**Issue by joglekau** [VivekanandanS/strapi-provider-upload-aws-s3-cdn#1]
Hello community,

Can someone explain to me why in lib/index.js: line 41 the file.url is set to `${config.cdn}${data.Key}`? This AWS CDN provider is amazing, but now when I get my data response, I'm having to do a .replace(.cloudfront.net/g, ".cloudfront.net/") because the URL is missing a "/".

Is there a good reason to do that, or is that just a bug?

Thank you,
Uddhav Joglekar
Software Engineer
Moody's Analytics

**Comment by couragecowardlydog** [comment]
In config, you can configure however you want, sometimes just with cloudfront other times with the folder path

**Comment by joglekau** [comment]
Oh you're right! This was a very silly question, thanks for your help!
